[build]
  command = "composer install"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
  force = true

[[redirects]]
  from = "/backend/*"
  to = "/backend/:splat"
  status = 200
  force = true
